# Generated by Django 4.0.6 on 2022-07-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NimapApp', '0002_mynimapinfo_client_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mynimapinfo',
            name='client',
        ),
        migrations.AddField(
            model_name='mynimapinfo',
            name='project',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ProjectInfo',
        ),
    ]
